### ISSUE TITLE
Update the Hand Wave in Ringer Desing

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/Lif-Official-Site#11]
Change the hand-waving icon in the new Ringer design as this image may be copyrighted.

**Tasks**

- [x] Desing a new hand-waving icon
- [x] Update Figma design with new icon
- [x] Update Figma design on Ringer about page
